"""add social account credentials fields

Revision ID: 211f164682dc
Revises: 61985b5bc97b
Create Date: 2026-08-14 16:09:30.451033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211f164682dc'
down_revision: Union[str, Sequence[str], None] = '61985b5bc97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('social_accounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('social_accounts', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('social_accounts', 'account_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('social_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('social_accounts', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'connected'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_accounts', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'connected'::character varying"))
    op.alter_column('social_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('social_accounts', 'account_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('social_accounts', 'token_expires_at')
    op.drop_column('social_accounts', 'refresh_token')
    op.drop_column('social_accounts', 'username')
    # ### end Alembic commands ###
